# This is a basic workflow build and deploy ACE Applications

name: ACE Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run Docker container to compile assets
        uses: addnab/docker-run-action@v3
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          registry: ${{secrets.REGISTRY}}
          image: ${{secrets.IMAGE}}
          options: -v ${{ github.workspace }}:/app -u root
          run: |
            cd ../..
            chmod 777 -R ./app
            #ls -al opt/ibm/ace-12/server/bin/
            
            export LICENSE=accept
            export MQSI_WORKPATH=$PWD/var/mqsi
            . /opt/ibm/ace-12/server/bin/mqsiprofile
            
            export ACE_BIN_PATH=./opt/ibm/ace-12/server/bin/
            
            $ACE_BIN_PATH/ibmint package --input-path /app/HTTPInputApplication/ --output-bar-file /app/GeneratedBarFiles/testbar.bar
            #$ACE_BIN_PATH/mqsipackagebar -w . -a app/GeneratedBarFiles/testbar.bar -o app/HTTPInputApplication/HTTPInputMessageFlow.msgflow -k ./app/HTTPInputApplication
            $ACE_BIN_PATH/mqsiapplybaroverride -b app/GeneratedBarFiles/testbar.bar -p app/properties/DEV.properties -o app/GeneratedBarFiles/testbar_DEV.bar -r
            $ACE_BIN_PATH/mqsiapplybaroverride -b app/GeneratedBarFiles/testbar.bar -p app/properties/QA.properties -o app/GeneratedBarFiles/testbar_QA.bar -r
            
            $ACE_BIN_PATH/ibmint package --input-path /app/HTTPInputApplicationTest/ --output-bar-file /app/GeneratedBarFiles/unittest.bar
            $ACE_BIN_PATH/mqsicreateworkdir /app/workdir
            $ACE_BIN_PATH/ibmint deploy --input-bar-file /app/GeneratedBarFiles/unittest.bar --output-work-dir /app/workdir
            $ACE_BIN_PATH/ibmint deploy --input-bar-file /app/GeneratedBarFiles/testbar.bar --output-work-dir /app/workdir

            cd app
            ls 
            #$ACE_BIN_PATH/IntegrationServer --work-dir /app/workdir/
            ../opt/ibm/ace-12/server/bin/IntegrationServer --work-dir workdir --test-project HTTPInputApplicationTest --start-msgflows false
            
            
      - name: Check
        run: |
          ls -al GeneratedBarFiles          
          #chmod 777 -R GeneratedBarFiles
          git config --global user.name "HolaJinn"
          git config --global user.email "HolaJinn@users.noreply.github.com"
          git add GeneratedBarFiles/testbar.bar
          git commit -m "Add bar files"
          git push
     
